import NavBar from "@/app/components/NavBar";
import { PrismaClient } from "@prisma/client";
import { Metadata } from "next";
import React from "react";
import Header from "../components/Header";
import Menu from "../components/Menu";
import RestaurantNavbar from "../components/RestaurantNavbar";

export const metadata: Metadata = {
  title: "Menu of Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchItems = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      Items: true,
    },
  });

  if (restaurant === null) {
    throw new Error();
  }

  return restaurant.Items;
};

async function MenuPage({ params: { slug } }: { params: { slug: string } }) {
  const menu = await fetchItems(slug);
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavbar slug={slug} />
        <Menu menu={menu} />
      </div>
    </>
  );
}

export default MenuPage;
