import NavBar from "@/app/components/NavBar";
import { Metadata } from "next";
import React from "react";
import Header from "../components/Header";
import Menu from "../components/Menu";
import RestaurantNavbar from "../components/RestaurantNavbar";

export const metadata: Metadata = {
  title: "Menu of Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

function MenuPage() {
  return (
    <>
     
        <div className="bg-white w-[100%] rounded p-3 shadow">
          <RestaurantNavbar />
          <Menu />
        </div>
    </>
  );
}

export default MenuPage;
