import React from "react";
import Link from "next/link";
import NavBar from "@/app/components/NavBar";
import Header from "./components/Header";
import { Metadata } from "next";
import Form from "./components/Form";
import { PrismaClient } from "@prisma/client";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Reserve at Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchRestaurantBySlug = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
  });

  if (!restaurant) {
    notFound();
  }

  return restaurant;
};

async function ReserveShakeshack({
  params: { slug },
  searchParams,
}: {
  params: {
    slug: string;
    time: string;
  };
  searchParams: { date: string; partySize: string };
}) {
  const restaurant = await fetchRestaurantBySlug(slug);
  return (
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header
          image={restaurant.main_image}
          name={restaurant.name}
          date={searchParams.date}
          partySize={searchParams.partySize}
        />
        <Form
          date={searchParams.date}
          partySize={searchParams.partySize}
          slug={slug}
        />
      </div>
    </div>
  );
}

export default ReserveShakeshack;
