import React from "react";
import Link from "next/link";
import NavBar from "@/app/components/NavBar";
import Header from "./components/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reserve at Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

function ReserveShakeshack() {
  return (
    <div className="border-t h-screen">
      <div className="py-9 w-3/5 m-auto">
        <Header />
        <div className="mt-10 flex flex-wrap justify-between w-[660px]">
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="First name"
          />
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="Last name"
          />
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="Phone number"
          />
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="Email"
          />
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="Occasion (optional)"
          />
          <input
            type="text"
            className="border rounded p-3 w-80 mb-4"
            placeholder="Requests (optional)"
          />
          <button className="bg-red-600 w-full p-3 text-white font-bold rounded disabled:bg-gray-300">
            Complete reservation
          </button>
          <p className="mt-4 text-sm">
            By clicking “Complete reservation” you agree to the OpenTable Terms
            of Use and Privacy Policy. Standard text message rates may apply.
            You may opt out of receiving text messages at any time.
          </p>
        </div>
      </div>
    </div>
  );
}

export default ReserveShakeshack;
