import NavBar from "@/app/components/NavBar";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
import Description from "./components/Description";
import Header from "./components/Header";
import Images from "./components/Images";
import Raiting from "./components/Raiting";
import ReservationCard from "./components/ReservationCard";
import RestaurantNavbar from "./components/RestaurantNavbar";
import Reviews from "./components/Reviews";
import Title from "./components/Title";

export const metadata: Metadata = {
  title: "Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

function ShakeShack() {
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavbar />
        <Title />
        <Raiting />
        <Description />
        <Images />
        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
}

export default ShakeShack;
