import NavBar from "@/app/components/NavBar";
import { PrismaClient } from "@prisma/client";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
import Description from "./components/Description";
import Header from "./components/Header";
import Images from "./components/Images";
import Raiting from "./components/Raiting";
import ReservationCard from "./components/ReservationCard";
import RestaurantNavbar from "./components/RestaurantNavbar";
import Reviews from "./components/Reviews";
import Title from "./components/Title";

export const metadata: Metadata = {
  title: "Milestole Toronto | Open Table",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

interface Restaurant {
  id: number;
  name: string;
  images: string[];
  description: string;
  slug: string;
}

const fetchRestaurant = async (slug: string): Promise<Restaurant> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: { slug },
    select: {
      id: true,
      name: true,
      images: true,
      description: true,
      slug: true,
    },
  });

  if (restaurant === null) {
    throw new Error();
  }

  return restaurant;
};

async function RestaurantDetail({
  params: { slug },
}: {
  params: { slug: string };
}) {
  // console.log(props);
  const restaurant = await fetchRestaurant(slug);
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavbar slug={restaurant.slug} />
        <Title name={restaurant.name} />
        <Raiting />
        <Description description={restaurant.description} />
        <Images images={restaurant.images} />
        <Reviews />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  );
}

export default RestaurantDetail;
